FROM arm64v8/alpine:3.20

RUN apk update
RUN apk add gcc g++ build-base cmake git wget ninja-build ninja-is-really-ninja nano sed linux-headers perl mold
RUN mkdir -p /opt/ichor/build

WORKDIR /opt/ichor/build

ENTRYPOINT ["/bin/sh", "-c"]

CMD ["cd /opt/ichor/build && cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DICHOR_BUILD_EXAMPLES=OFF -DICHOR_BUILD_TESTING=OFF -DICHOR_MUSL=1 -DICHOR_AARCH64=1 -DICHOR_ARCH_OPTIMIZATION=RASPBERRY_PI_FOUR -DICHOR_USE_MOLD=1 /opt/ichor/src && ninja"]
