#include <ichor/services/network/http/HttpInternal.h>

namespace Ichor::v1 {
    unordered_map<std::string_view, HttpMethod> ICHOR_METHOD_MATCHING {
        {"DELETE", HttpMethod::delete_},
        {"GET", HttpMethod::get},
        {"HEAD", HttpMethod::head},
        {"POST", HttpMethod::post},
        {"PUT", HttpMethod::put},
        {"CONNECT", HttpMethod::connect},
        {"OPTIONS", HttpMethod::options},
        {"TRACE", HttpMethod::trace},
        {"COPY", HttpMethod::copy},
        {"LOCK", HttpMethod::lock},
        {"MKCOL", HttpMethod::mkcol},
        {"MOVE", HttpMethod::move},
        {"PROPFIND", HttpMethod::propfind},
        {"PROPPATCH", HttpMethod::proppatch},
        {"SEARCH", HttpMethod::search},
        {"UNLOCK", HttpMethod::unlock},
        {"BIND", HttpMethod::bind},
        {"REBIND", HttpMethod::rebind},
        {"UNBIND", HttpMethod::unbind},
        {"ACL", HttpMethod::acl},
        {"REPORT", HttpMethod::report},
        {"MKACTIVITY", HttpMethod::mkactivity},
        {"CHECKOUT", HttpMethod::checkout},
        {"MERGE", HttpMethod::merge},
        {"MSEARCH", HttpMethod::msearch},
        {"NOTIFY", HttpMethod::notify},
        {"SUBSCRIBE", HttpMethod::subscribe},
        {"UNSUBSCRIBE", HttpMethod::unsubscribe},
        {"PATCH", HttpMethod::patch},
        {"PURGE", HttpMethod::purge},
        {"MKCALENDAR", HttpMethod::mkcalendar},
        {"LINK", HttpMethod::link},
        {"UNLINK", HttpMethod::unlink},
    };
    unordered_map<HttpMethod, std::string_view> ICHOR_REVERSE_METHOD_MATCHING {
        {HttpMethod::delete_, "DELETE"},
        {HttpMethod::get, "GET"},
        {HttpMethod::head, "HEAD"},
        {HttpMethod::post, "POST"},
        {HttpMethod::put, "PUT"},
        {HttpMethod::connect, "CONNECT"},
        {HttpMethod::options, "OPTIONS"},
        {HttpMethod::trace, "TRACE"},
        {HttpMethod::copy, "COPY"},
        {HttpMethod::lock, "LOCK"},
        {HttpMethod::mkcol, "MKCOL"},
        {HttpMethod::move, "MOVE"},
        {HttpMethod::propfind, "PROPFIND"},
        {HttpMethod::proppatch, "PROPPATCH"},
        {HttpMethod::search, "SEARCH"},
        {HttpMethod::unlock, "UNLOCK"},
        {HttpMethod::bind, "BIND"},
        {HttpMethod::rebind, "REBIND"},
        {HttpMethod::unbind, "UNBIND"},
        {HttpMethod::acl, "ACL"},
        {HttpMethod::report, "REPORT"},
        {HttpMethod::mkactivity, "MKACTIVITY"},
        {HttpMethod::checkout, "CHECKOUT"},
        {HttpMethod::merge, "MERGE"},
        {HttpMethod::msearch, "MSEARCH"},
        {HttpMethod::notify, "NOTIFY"},
        {HttpMethod::subscribe, "SUBSCRIBE"},
        {HttpMethod::unsubscribe, "UNSUBSCRIBE"},
        {HttpMethod::patch, "PATCH"},
        {HttpMethod::purge, "PURGE"},
        {HttpMethod::mkcalendar, "MKCALENDAR"},
        {HttpMethod::link, "LINK"},
        {HttpMethod::unlink, "UNLINK"},
    };
    unordered_map<HttpStatus, std::string_view> ICHOR_STATUS_MATCHING {
        {HttpStatus::continue_, "Continue"},
        {HttpStatus::switching_protocols, "Switching Protocols"},
        {HttpStatus::processing, "Processing"},
        {HttpStatus::ok, "OK"},
        {HttpStatus::created, "Created"},
        {HttpStatus::accepted, "Accepted"},
        {HttpStatus::non_authoritative_information, "Non Authoritative Information"},
        {HttpStatus::no_content, "No Content"},
        {HttpStatus::reset_content, "Reset Content"},
        {HttpStatus::partial_content, "Partial Content"},
        {HttpStatus::multi_status, "Multi Status"},
        {HttpStatus::already_reported, "Already Reported"},
        {HttpStatus::im_used, "IM Used"},
        {HttpStatus::multiple_choices, "Multiple Choices"},
        {HttpStatus::moved_permanently, "Moved Permanently"},
        {HttpStatus::found, "Found"},
        {HttpStatus::see_other, "See Other"},
        {HttpStatus::not_modified, "Not Modified"},
        {HttpStatus::use_proxy, "Use Proxy"},
        {HttpStatus::temporary_redirect, "Temporary Redirect"},
        {HttpStatus::permanent_redirect, "Permanent Redirect"},
        {HttpStatus::bad_request, "Bad Request"},
        {HttpStatus::unauthorized, "Unauthorized"},
        {HttpStatus::payment_required, "Payment Required"},
        {HttpStatus::forbidden, "Forbidden"},
        {HttpStatus::not_found, "Not Found"},
        {HttpStatus::method_not_allowed, "Method Not Allowed"},
        {HttpStatus::not_acceptable, "Not Acceptable"},
        {HttpStatus::proxy_authentication_required, "Proxy Authentication Required"},
        {HttpStatus::request_timeout, "Request Timeout"},
        {HttpStatus::conflict, "Conflict"},
        {HttpStatus::gone, "Gone"},
        {HttpStatus::length_required, "Length Required"},
        {HttpStatus::precondition_failed, "Precondition Failed"},
        {HttpStatus::payload_too_large, "Payload Too Large"},
        {HttpStatus::uri_too_long, "URI Too Long"},
        {HttpStatus::unsupported_media_type, "Unsupported Media Type"},
        {HttpStatus::range_not_satisfiable, "Range Not Satisfiable"},
        {HttpStatus::expectation_failed, "Expectation Failed"},
        {HttpStatus::misdirected_request, "Misdirected Request"},
        {HttpStatus::unprocessable_entity, "Unprocessable Entity"},
        {HttpStatus::locked, "Locked"},
        {HttpStatus::failed_dependency, "Failed Dependency"},
        {HttpStatus::upgrade_required, "Upgrade Required"},
        {HttpStatus::precondition_required, "Precondition Required"},
        {HttpStatus::too_many_requests, "Too Many Requests"},
        {HttpStatus::request_header_fields_too_large, "Request Header Fields Too Large"},
        {HttpStatus::connection_closed_without_response, "Connection Closed Without Response"},
        {HttpStatus::unavailable_for_legal_reasons, "Unavailable For Legal Reasons"},
        {HttpStatus::client_closed_request, "Client Closed Request"},
        {HttpStatus::internal_server_error, "Internal Server Error"},
        {HttpStatus::not_implemented, "Not Implemented"},
        {HttpStatus::bad_gateway, "Bad Gateway"},
        {HttpStatus::service_unavailable, "Service Unavailable"},
        {HttpStatus::gateway_timeout, "Gateway Timeout"},
        {HttpStatus::http_version_not_supported, "HTTP Version Not Supported"},
        {HttpStatus::variant_also_negotiates, "Variant Also Negotiates"},
        {HttpStatus::insufficient_storage, "Insufficient Storage"},
        {HttpStatus::loop_detected, "Loop Detected"},
        {HttpStatus::not_extended, "Not Extended"},
        {HttpStatus::network_authentication_required, "Network Authentication Required"},
        {HttpStatus::network_connect_timeout_error, "Network Connect Timeout Error"},
    };
}
